import { ScanningResults, ScanningSummary } from '@handlers/cli/types/scan.mode'
import { useCliRun } from '@hooks/useCliRun'
import {
  getFolderName,
  getParentFolderPath,
  humanizeSize,
  normalizeFolderPath
} from '@utils/strings'
import { useEffect, useMemo, useState } from 'react'
import { ScanningLoader } from '../scanningLoader'
import { FolderNode, FolderTree } from './summaryFolder'
import { SummaryItem } from './summaryItem'

function sortFolderTreeInPlace(nodes: FolderNode[]): void {
  nodes.sort((a, b) => a.name.localeCompare(b.name))
  for (const n of nodes) {
    sortFolderTreeInPlace(n.children)
  }
}

function buildTree(folders: ScanningResults['folders'], root: string): FolderNode[] {
  const rootNorm = normalizeFolderPath(root)
  const nodeMap = new Map<string, FolderNode>()

  for (const folder of folders) {
    if (!folder.path.trim()) continue
    const pathNorm = normalizeFolderPath(folder.path)
    if (pathNorm === rootNorm || pathNorm === '') continue

    // key is normalized for reliable lookup; path retains original for display
    nodeMap.set(pathNorm, {
      path: folder.path,
      name: getFolderName(folder.path),
      size: folder.recursive_bytes,
      files: folder.direct_files,
      children: []
    })
  }

  const roots: FolderNode[] = []

  for (const node of nodeMap.values()) {
    const parentPath = getParentFolderPath(node.path)
    const parent = nodeMap.get(parentPath)
    if (parent) {
      parent.children.push(node)
    } else {
      roots.push(node)
    }
  }

  sortFolderTreeInPlace(roots)
  return roots
}

function collectAllPaths(nodes: FolderNode[]): string[] {
  return nodes.flatMap((n) => [n.path, ...collectAllPaths(n.children)])
}

export const ScanningSummaryPanel = (): React.JSX.Element => {
  const { summary } = useCliRun()

  const [summaryResults, setSummaryResults] = useState<ScanningResults | null>(null)
  const [expanded, setExpanded] = useState<Record<string, boolean>>({})

  // Read the JSON summary results generated by the CLI
  useEffect(() => {
    if (summary && summary.action === 'scan') {
      const { report_path } = summary as ScanningSummary
      const results = window.appApi.cli.readSummaryResult<ScanningResults>(report_path)
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setSummaryResults(results)
    }
  }, [summary])

  // Build the folder tree from the summary results
  const tree = useMemo(() => {
    if (!summaryResults) return []
    return buildTree(summaryResults.folders, summaryResults.root)
  }, [summaryResults])

  const allPaths = useMemo(() => collectAllPaths(tree), [tree])
  const isAnyExpanded = Object.values(expanded).some(Boolean)

  const handleExpandToggle = (path: string): void => {
    setExpanded((prev) => ({ ...prev, [path]: !prev[path] }))
  }

  const handleExpandCollapse = (): void => {
    if (isAnyExpanded) {
      setExpanded({})
    } else {
      setExpanded(Object.fromEntries(allPaths.map((p) => [p, true])))
    }
  }

  if (!summaryResults) {
    return <ScanningLoader show={true} progress={0} label="Loading summary..." />
  }

  const { total_files, folder_count, total_bytes } = summaryResults

  return (
    <div className="flex min-h-0 flex-1 flex-row items-stretch gap-2 py-2 pr-1">
      <div className="flex min-h-0 min-w-0 flex-1 flex-row items-stretch max-w-[300px]">
        <div className="flex flex-1 h-fit w-full flex-col items-start justify-start bg-surface gap-2 text-outline-dim rounded-md p-2 px-3">
          <span className="text-xs font-semibold text-primary w-full mb-2 pb-2 border-b border-outline-variant uppercase">
            Scan Summary
          </span>
          <SummaryItem label="Scanned Folders" value={folder_count.toLocaleString()} />
          <SummaryItem label="Files Found" value={total_files.toLocaleString()} />
          <SummaryItem label="Total Size" value={humanizeSize(total_bytes)} />
        </div>
      </div>

      <div className="flex min-h-0 min-w-0 flex-2 flex-col items-start rounded-md shadow-card bg-surface py-2 px-2 gap-2 overflow-hidden">
        <div className="flex flex-row items-center justify-between w-full pl-2 pb-2">
          <span className="text-lg font-semibold text-primary capitalize">
            Discovered Structure
          </span>
          <button
            onClick={handleExpandCollapse}
            className="text-xs text-primary font-medium hover:underline cursor-pointer"
          >
            {isAnyExpanded ? 'Collapse all' : 'Expand all'}
          </button>
        </div>

        <div className="flex flex-col items-start bg-transparent justify-start w-full min-w-0 gap-2 overflow-y-auto p-2">
          <FolderTree nodes={tree} depth={0} expanded={expanded} onToggle={handleExpandToggle} />
        </div>
      </div>
    </div>
  )
}
